package com.interview.intterviewbit.dynamicprogram;

/**
 * Given a string, find if there is any sub-sequence that repeats itself. A
 * sub-sequence of a string is defined as a sequence of characters generated by
 * deleting some characters in the string without changing the order of the
 * remaining characters.
 * 
 * @author jojo
 *
 */
public class RepeatingSubSequence
{
	public int repeatExist(String s)
	{
		int[][] grid = new int[s.length() + 1][s.length() + 1];

		for (int i = 1; i <= s.length(); i++)
		{
			for (int j = i; j <= s.length(); j++)
			{
				if (s.charAt(i - 1) == s.charAt(j - 1) && j != i)
				{
					grid[i][j] = 1 + grid[i - 1][j - 1];
				}
				else
				{
					grid[i][j] = Math.max(grid[i - 1][j], grid[i][j - 1]);
				}
			}
		}

		if (grid[s.length()][s.length()] > 1)
		{
			return 1;
		}

		return 0;
	}

	public static void main(String[] args)
	{
		int r = new RepeatingSubSequence().repeatExist("aabb");
		System.out.println(r);
	}
}
